# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
# Without a Run Workflow button, this is my only option, for 32 times now.

name: Build EMUTIL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  page_build:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant clean compile
    - name: Deploy elsewhere
      uses: snxd/deploy-github-deploy-action@Use-Setup-Action
      with:
        working_directory: 'bin/'
        console_version: '6.1.2.51'
        scripts_version: '3.7.18'
        target_product: 'Emutil'
        target_environment: 'Java'
        target_repository: 'Bin'
        solsta_client_id:  ${{ secrets.SNXD_CLIENT_ID }}
        solsta_client_secret:  ${{ secrets.SNXD_CLIENT_SECRET }}
  
        
